Ecommerce/Models/ActorModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace Ecommerce.Models
{
    public class ActorModel
    {
        [Key]
        public int Id  { get; set; }

        [Display(Name = "Profile Picture Url")]
        [Required(ErrorMessage = "Profile Picture is required")]
        public string ProfilePicture { get; set; }
        [Display(Name = "Full Name")]
        [Required(ErrorMessage = "Full Name is required")]
        [StringLength(50, MinimumLength = 3, ErrorMessage =  "Full name must between 3 to 50 char")]
        public string FullName { get; set; }
        [Display(Name = "Biography")]
        [Required(ErrorMessage = "Biography is required")]
        public string Bio { get; set; }

        //Relationship

        public List<Actor_Movies> Actor_Movies { get; set; }



    }
}

Ecommerce/Models/Actor_Movies.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Ecommerce.Models
{
    public class Actor_Movies
    {

        public int MovieId { get; set; }
        public MoviesModel Movie { get; set; }
        public int ActorId { get; set; }
        public ActorModel Actor { get; set; }
    }
}

Ecommerce/Models/CinemaModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace Ecommerce.Models
{
    public class CinemaModel
    {
        [Key]
        public int MyProperty { get; set; }
        [Display(Name = "Cinema Logo")]
        public string Logo { get; set; }
        [Display(Name = "Cinema Name")]
        public string Name { get; set; }
        [Display(Name = "Description")]
        public string Description { get; set; }


        //Relationship
        public List<MoviesModel> Movies { get; set; }

    }
}

Ecommerce/Models/ErrorViewModel.cs
using System;

namespace Ecommerce.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Ecommerce/Models/MoviesModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;
using Ecommerce.Data;

namespace Ecommerce.Models
{
    public class MoviesModel
    {
        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Price { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        public string Image { get; set; }
        public MovieCategory MovieCategory { get; set; }


        //Relationship

        public List<Actor_Movies> Actor_Movies { get; set; }
        
        //Cinema
        public int CinemaId { get; set; }
        [ForeignKey("CinemaId")] 
        public CinemaModel Cinema { get; set; }


        //Producer
        public int ProducerId { get; set; }
        [ForeignKey("ProducerId ")]
        public ProducersModel Producer { get; set; }





    }
}

Ecommerce/Models/ProducersModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace Ecommerce.Models
{
    public class ProducersModel
    {
        [Key]
        public int Id { get; set; }
        [Display(Name = "Profile Picture")]
        public string ProfilePicture { get; set; }
        [Display(Name = "Full Name")]
        public string FullName { get; set; }
        [Display(Name = "Biography")]
        public string Bio { get; set; }

        // Relationship 
        public List<MoviesModel> Movies { get; set; }
    }
}

Ecommerce/Controllers/ActorController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Ecommerce.Data;
using Ecommerce.Data.Services;
using Ecommerce.Models;

namespace Ecommerce.Controllers
{
    public class ActorController : Controller
    {
        private readonly  IActorService _service;

         public ActorController(IActorService service)
        {
            _service = service;
        }

        public async Task<IActionResult> Index()
        {
            var data = await _service.GetAllAsync();
            return View(data);
        }

        //add new actor ali 22/10/2022
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("FullName,ProfilePicture,Bio")] ActorModel actor)
        {
            if (!ModelState.IsValid)
            {
                return View(actor);
            }
            await _service.AddAsync(actor);
            return RedirectToAction(nameof(Index));
        }

        // To check the details 
        public async Task<IActionResult> Details(int id)
        {
            var actorDetails = await _service.GetByIdAsync(id);

            if (actorDetails == null) return View("NotFound");
            return View(actorDetails);
        }

        //update existing  actor ali 22/10/2022
        public async Task<IActionResult> Edit(int id)
        {
            var actorDetails = await _service.GetByIdAsync(id);
            if (actorDetails == null) return View("NotFound");

            return View(actorDetails);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id,[Bind("Id,FullName,ProfilePicture,Bio")] ActorModel actor)
        {
            if (!ModelState.IsValid)
            {
                return View(actor);
            }
            await _service.UpdateAsync(id,actor);
            return RedirectToAction(nameof(Index));
        }

        //Delete existing  actor ali 22/10/2022
        public async Task<IActionResult> Delete(int id)
        {
            var actorDetails = await _service.GetByIdAsync(id);
            if (actorDetails == null) return View("NotFound");

            return View(actorDetails);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirm(int id)
        {
            var actorDetails = await _service.GetByIdAsync(id);
            if (actorDetails == null) return View("NotFound");
            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

Ecommerce/Controllers/CinemaController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Ecommerce.Data;
using Microsoft.EntityFrameworkCore;

namespace Ecommerce.Controllers
{
    public class CinemaController : Controller
    {
        private readonly AppDbContext _context;

        public CinemaController(AppDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var allCinemas = await _context.cinemas.ToListAsync();
            return View(allCinemas);
        }
    }
}

Ecommerce/Controllers/MoviesController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Ecommerce.Data;

namespace Ecommerce.Controllers
{
    public class MoviesController : Controller
    {
        private readonly AppDbContext _context;

        public MoviesController(AppDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var allMovies = await _context.movies.Include(n => n.Cinema).OrderBy(n => n.Name).ToListAsync();
            return View(allMovies);
        }
    }
}

Ecommerce/Controllers/ProducerController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Ecommerce.Data;
using Microsoft.EntityFrameworkCore;

namespace Ecommerce.Controllers
{
    public class ProducerController : Controller
    {

        private readonly AppDbContext _context;

        public ProducerController(AppDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var allProducers = await _context.Producers.ToListAsync();
            return View(allProducers);
        }
    }
}

Ecommerce/Views/Actor/Create.cshtml
 @model ActorModel


@{ 
    ViewData["Title"] = "Add a new actor";
}


<div class="row text">
    <div class="col-md-8 offset-2">
        
        <p>
            <h1> Add a New Actor</h1>
        </p>
        
        <div class="row">
            <div class="col-md-8 offset-2">
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group text-center">
                        <img class="border-info rounded-circle " style="max-width:150px" id="ProfilePictureReview" />
                    </div>
                    <div class="form-group">
                        <label asp-for="ProfilePicture" class="control-label"></label>
                        <input asp-for="ProfilePicture" class="form-control" />
                        <span asp-validation-for="ProfilePicture" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="FullName" class="control-label"></label>
                        <input asp-for="FullName" class="form-control" />
                        <span asp-validation-for="FullName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Bio" class="control-label"></label>
                        <input asp-for="Bio" class="form-control" />
                        <span asp-validation-for="Bio" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Create" class="btn btn-outline-success float-right" />
                        <a class="btn btn-outline-secondary" asp-action="Index"> Show All</a>
                    </div>


                </form>
            </div>
        </div>
    </div>
</div>



@section Scripts{
    <script>

        $(document).ready(function () {
            var output = document.getElementById('ProfilePictureReview');
            output.src = $("#ProfilePictureReview").val();
        })



        $("#ProfilePictureReview").on("change", function () {
            var output = document.getElementById('ProfilePictureReview');
            output.src = $(this).val();
        })


    </script>


}

Ecommerce/Views/Actor/Delete.cshtml
@model ActorModel


@{
    ViewData["Title"] = "Delete actor";
}


<div class="row text">
    <div class="col-md-8 offset-2">

        <p>
            <h1> Delete Confirmation for @Model.FullName</h1>
        </p>

        <div class="row">
            <div class="col-md-8 offset-2">
               
                    <div class="form-group text-center">
                        <img class="border-info rounded-circle " style="max-width:150px" id="ProfilePictureReview" />
                    </div>
                    <div class="form-group">
                        <label asp-for="ProfilePicture" class="control-label"></label>
                        <input asp-for="ProfilePicture" class="form-control" readonly />
                        <span asp-validation-for="ProfilePicture" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="FullName" class="control-label"></label>
                        <input asp-for="FullName" class="form-control" readonly />
                        <span asp-validation-for="FullName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Bio" class="control-label"></label>
                        <input asp-for="Bio" class="form-control"  readonly />
                        <span asp-validation-for="Bio" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <form asp-action="Delete" >
                            <input type="hidden" asp-for="Id"/>
                            <input type="submit" value="Confirm" class="btn btn-danger float-right"/>
                        </form>
                        <a class="btn btn-outline-secondary" asp-action="Index"> Show All</a>
                    </div>
            </div>
        </div>
    </div>
</div>



@section Scripts{
    <script>

        $(document).ready(function () {
            var output = document.getElementById('ProfilePictureReview');
            output.src = $("#ProfilePictureReview").val();
        })
    </script>


}

Ecommerce/Views/Actor/Details.cshtml
@model ActorModel


@{
    ViewData["Title"] = "Add a new actor";
}


<div class="row text">
    <div class="col-md-8 offset-2">

        <p>
            <h1> Details for @Model.FullName</h1>
        </p>

        <div class="row">
            <div class="col-md-8 offset-2">
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group text-center">
                        <img class="border-info rounded-circle " style="max-width:150px" id="ProfilePictureReview" />
                    </div>
                    <div class="form-group">
                        <label asp-for="ProfilePicture" class="control-label"></label>
                        <input asp-for="ProfilePicture" class="form-control" readonly />
                        <span asp-validation-for="ProfilePicture" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="FullName" class="control-label"></label>
                        <input asp-for="FullName" class="form-control" readonly />
                        <span asp-validation-for="FullName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Bio" class="control-label"></label>
                        <input asp-for="Bio" class="form-control"  readonly />
                        <span asp-validation-for="Bio" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <a class="btn btn-outline-secondary" asp-action="Index"> Show All</a>
                    </div>


                </form>
            </div>
        </div>
    </div>
</div>



@section Scripts{
    <script>

        $(document).ready(function () {
            var output = document.getElementById('ProfilePictureReview');
            output.src = $("#ProfilePictureReview").val();
        })
    </script>


}

Ecommerce/Views/Actor/Edit.cshtml
 @model ActorModel


@{ 
    ViewData["Title"] = "Update actor";
}


<div class="row text">
    <div class="col-md-8 offset-2">
        
        <p>
            <h1> Update Actor</h1>
        </p>
        
        <div class="row">
            <div class="col-md-8 offset-2">
                <form asp-action="Edit">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group text-center">
                        <img class="border-info rounded-circle " style="max-width:150px" id="ProfilePictureReview" />
                    </div>
                    <div class="form-group">
                        <label asp-for="ProfilePicture" class="control-label"></label>
                        <input asp-for="ProfilePicture" class="form-control" />
                        <span asp-validation-for="ProfilePicture" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="FullName" class="control-label"></label>
                        <input asp-for="FullName" class="form-control" />
                        <span asp-validation-for="FullName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Bio" class="control-label"></label>
                        <input asp-for="Bio" class="form-control" />
                        <span asp-validation-for="Bio" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Update" class="btn btn-outline-success float-right" />
                        <a class="btn btn-outline-secondary" asp-action="Index"> Show All</a>
                    </div>


                </form>
            </div>
        </div>
    </div>
</div>



@section Scripts{
    <script>

        $(document).ready(function () {
            var output = document.getElementById('ProfilePictureReview');
            output.src = $("#ProfilePictureReview").val();
        })



        $("#ProfilePictureReview").on("change", function () {
            var output = document.getElementById('ProfilePictureReview');
            output.src = $(this).val();
        })


    </script>


}

Ecommerce/Views/Actor/Index.cshtml
@*Model
    Csharp
    HTML*@

@model IEnumerable<ActorModel>

@*Define ViewData*@
@{
    ViewData["Title"] = "List of Actors";

}

@*Write Code*@

<div class="row">
    <div class="col-md-8 offset-md-2">
        <table class="table">
            <thead>
                <tr class="text-center">
                    <th>@Html.DisplayNameFor(model => model.ProfilePicture)</th>
                    <th>@Html.DisplayNameFor(model => model.FullName)</th>
                    <th>@Html.DisplayNameFor(model => model.Bio)</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td class="align-middle">
                            <img class="rounded-circle" src="@item.ProfilePicture" alt="@item.FullName" style="max-width:150px" />
                        </td>
                        <td class="align-middle">
                            @Html.DisplayFor(modelItem => item.FullName)
                        </td>
                        <td class="align-middle">
                            @Html.DisplayFor(modelItem => item.Bio)
                        </td>
                        <td class="align-middle">
                            <a class="btn btn-outline-primary" asp-action="Edit" asp-route-id="@item.Id"><i class="bi bi-pencil-square"></i> Edit</a>
                            <a class="btn btn-outline-info" asp-action="Details" asp-route-id="@item.Id"><i class="bi bi-eye"></i> Details</a>
                            <a class="btn btn-danger" asp-action="Delete" asp-route-id="@item.Id"><i class="bi bi-pencil-square"></i> Delete</a>
                        </td>
                    </tr>
                }


            </tbody>
        </table>
    </div>

</div>


<div style="position:fixed; right: 25px; bottom: 125px;" class="text-white">
    <a asp-controller="Actor" asp-action="Create" class="btn btn-success">
        <i class="bi bi-plus"></i> Add New
    </a>
</div>

Ecommerce/Views/Cinema/Index.cshtml
@*Model
    Csharp
    HTML*@

@model IEnumerable<CinemaModel>

@*Define ViewData*@
@{
    ViewData["Title"] = "List of Cinemas";

}

@*Write Code*@

<div class="row">
    <div class="col-md-8 offset-md-2">
        <table class="table">
            <thead>
                <tr class="text-center">
                    <th>@Html.DisplayNameFor(model => model.Logo)</th>
                    <th>@Html.DisplayNameFor(model => model.Name)</th>
                    <th>@Html.DisplayNameFor(model => model.Description)</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td class="align-middle">
                            <img class="rounded-circle" src="@item.Logo" alt="@item.Name" style="max-width:150px" />
                        </td>
                        <td class="align-middle">
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td class="align-middle">
                            @Html.DisplayFor(modelItem => item.Description)
                        </td>
                        <td class="align-middle">
                            <a class="btn btn-outline-primary"><i class="bi bi-pencil-square"></i> Edit</a>
                            <a class="btn btn-outline-info"><i class="bi bi-eye"></i> Details</a>
                            <a class="btn btn-danger"><i class="bi bi-pencil-square"></i> Delete</a>
                        </td>
                    </tr>
                }


            </tbody>
            <tr>
                <td></td>
            </tr>
        </table>
    </div>

</div>

Ecommerce/Views/Movies/Index.cshtml
@*Model
    Csharp
    HTML*@

@model IEnumerable<MoviesModel>
@*Define ViewData*@
@{
    ViewData["Title"] = "List of Movies";

}

@*Write Code*@

<div class="row">
    @foreach (var item in Model)
    {
        <div class="col-md-4 col-xs-6 border-primary" mb-3>
            <div class="card mb-3" style="max-width:540px">
                <div class="row g-0">
                    <div class="col-md-12">
                        <div class="card-header text-white bg-info">
                            <p class="card-text">
                                <h5 class="card-title"> @item.Name <a class="text-white float-right"><i class="bi bi-pencil-square"></i></a></h5>
                            </p>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <img src="@item.Image" width="100%" alt="@item.Name" />
                    </div>
                    <div class="col-md-6">
                        <div class="card-body">
                            <p class="card-text">Description Sample</p>
                            <p class="card-text">Cinema: <b>@item.Cinema.Name</b></p>
                            <p class="card-text">Category: <b>@item.MovieCategory</b></p>
                            <p class="card-text">Start Date: <b>@item.StartDate.ToString("dd MMM yy")</b></p>
                            <p class="card-text">End Date: <b>@item.EndDate.ToString("dd MMM yy")</b></p>
                            <p class="card-text">
                                <b>Status: </b>
                                @if (DateTime.Now >= item.StartDate && DateTime.Now <= item.EndDate)
                                {
                                    <span class="badge bg-success text-white">AVAILABLE</span>
                                }
                                else if (DateTime.Now > item.EndDate)
                                {
                                    <span class="badge bg-danger text-white">EXPIRED</span>
                                }
                                else
                                {
                                    <span class="badge bg-primary text-white">UPCOMING</span>
                                }
                            </p>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="card-footer">
                            <p class="card-text">
                                <a class="btn btn-outline-primary float-right"><i class="bi bi-eye-fill"></i> Show Details</a>
                                <a class="btn btn-success text-white"><i class="bi bi-cart-plus"></i> Add to Cart (Price @item.Price.ToString())</a>
                            </p>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    }

</div>

Ecommerce/Views/Producer/Index.cshtml
@*Model
    Csharp
    HTML*@

@model IEnumerable<ProducersModel>


@*Define ViewData*@
@{
    ViewData["Title"] = "List of Producers";

}

@*Write Code*@

<div class="row">
    <div class="col-md-8 offset-md-2">
        <table class="table">
            <thead>
                <tr class="text-center">
                    <th>@Html.DisplayNameFor(model => model.ProfilePicture)</th>
                    <th>@Html.DisplayNameFor(model => model.FullName)</th>
                    <th>@Html.DisplayNameFor(model => model.Bio)</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td class="align-middle">
                            <img class="rounded-circle" src="@item.ProfilePicture" alt="@item.FullName" style="max-width:150px" />
                        </td>
                        <td class="align-middle">
                            @Html.DisplayFor(modelItem => item.FullName)
                        </td>
                        <td class="align-middle">
                            @Html.DisplayFor(modelItem => item.Bio)
                        </td>
                        <td class="align-middle">
                            <a class="btn btn-outline-primary"><i class="bi bi-pencil-square"></i> Edit</a>
                            <a class="btn btn-outline-info"><i class="bi bi-eye"></i> Details</a>
                            <a class="btn btn-danger"><i class="bi bi-pencil-square"></i> Delete</a>
                        </td>
                    </tr>
                }


            </tbody>
            <tr>
                <td></td>
            </tr>
        </table>
    </div>

</div>

Ecommerce/Views/Shared/NotFound.cshtml
<div class="row">
    <div class="col-md-6 offset-6">
        <h1 class="text-info">The page you requested not found</h1>
        <hr />
        <a class="btn btn-outline-success" asp-controller="Movies" asp-action="Index">Home Page</a>
    </div>
</div>

Ecommerce/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Ecommerce</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Movies" asp-action="Index">Ecommerce</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="navbar-nav flex-grow-1">
                            <a class="nav-link text-dark" asp-controller="Movies" asp-action="Index"><i class="badge-info bi-film"></i>Movies</a>
                        </li>
                         <li class="nav-item dropdown">
                             <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="bi bi-gear"></i> Management</a>
                             <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                 <a class="dropdown-item" asp-controller="Cinema" asp-action="Index"> <i class="bi bi-camera-reels"></i> Cinemas</a>
                                 <a class="dropdown-item" asp-controller="Producer" asp-action="Index"> <i class="bi bi-headset"></i> Producers</a>
                                 <a class="dropdown-item" asp-controller="Actor" asp-action="Index"> <i class="bi bi-person-square"></i> Actors</a>
                             </div>
                         </li>

                    </ul>

                    <form class="form-inline my-2 my-lg-0 " asp-controller="Movies" asp-action="Filter" style="padding-right:25px;" >
                        <input  name="searchString" type="text" class="form-control" placeholder="Search for a Movie..." />
                        <button class="btn btn-outline-success my-2 my-sm-0 " type="submit"><i class="bi bi-search"></i></button>
                    </form>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Ecommerce  
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>